// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Skin is the predicate function for skin builders.
type Skin func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserProfile is the predicate function for userprofile builders.
type UserProfile func(*sql.Selector)

// UserToken is the predicate function for usertoken builders.
type UserToken func(*sql.Selector)
